name: .NET

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Publish
      run: dotnet publish -f .net5.0 -o /publish/
    - name: Zip release
      uses: papeloto/action-zip@v1
      with:
        files: /publish/
        recursive: false  
        dest: release.zip
    - name: Create release  
      uses: ncipollo/release-action@v1
      with:
        tag: $GITHUB_RUN_NUMBER
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
